#!/usr/bin/env bash
################################################################################
clear-bash-profile-cache() {
    rm /tmp/bp_total
}
autogenerate-bash-snippets() {
    /Users/dougpa/dotfiles/utils/autogenerate-bash-snippets.sh
}
main() {
    eventinfo="$@"
    echo "EVENTINFO: $eventinfo"
    # echo "$(gdate) EVENTINFO: $eventinfo"

    clear-bash-profile-cache
    if [[ $eventinfo =~ sh_autogenerated.snippets ]]; 
    then # guard against the very file this thing modifies
        # ..., although it should be ignored.
        autogenerate-bash-snippets
    fi
}
main "$@"
